    const tourPackages=
    [{
        "activityName": "Skiing",
        "destinationName": "Gulmarg",
        "packageName": "Basic Skiing Course",
        "packageDescription": "A world without friction - skiing, one of the most graceful sports on the planet right now. If you want to test your limits or if it's adrenaline rush you are seeking, it’s the sport to pursue. Gulmarg has quickly become a popular destination for skiers and snowboarders around the world - from absolute beginners to experts - you'll find them all here in winter. ",
        "packageHighlights": "Certified Instructor & Completion Certificate, Daily Unlimited Gondola Pass and Competition",
        "startLocation": "Srinagar",
        "finishLocation": "Srinagar",
        "groupSize": 5,
        "activityLevel": "Moderate",
        "duration": 10,
        "budget": 40000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop",
        "accommodation": "Twin Sharing in a lodge for 10 days",
        "tripStatus": "Active"
    },

    {
        "activityName": "Skiing",
        "destinationName": "Gulmarg",
        "packageName": "Intermediate Skiing Course",
        "packageDescription": "A world without friction - skiing, one of the most graceful sports on the planet right now. If you want to test your limits or if it's adrenaline rush you are seeking, it’s the sport to pursue. Gulmarg has quickly become a popular destination for skiers and snowboarders around the world - from absolute beginners to experts - you'll find them all here in winter. ",
        "packageHighlights": "Certified Instructor & Completion Certificate, Daily Unlimited Gondola Pass and Competition",
        "startLocation": "Srinagar",
        "finishLocation": "Srinagar",
        "groupSize": 5,
        "activityLevel": "Difficult",
        "duration": 7,
        "budget": 45000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop",
        "accommodation": "Twin Sharing in a lodge for 7 days",
        "tripStatus": "Active"
    },

    {
        "activityName": "Skiing",
        "destinationName": "Manali",
        "packageName": "Backcountry Skiing Expedition",
        "packageDescription": "Winters bring an all-new edge to the beauty of Manali by adding the pearly white colour to the whole city. And the best place to see the effect that snow brings to this serene city is to visit the amazing Solang Valley or Solang Nallah. A hotspot for paragliding and zorbing, the valley doubles as a snowy resort in the winters, attracting visitors to try their hands at some Manali skiing.",
        "packageHighlights": "Expedition support and experienced guides",
        "startLocation": "Palchan",
        "finishLocation": "Manali",
        "groupSize": 7,
        "activityLevel": "Difficult",
        "duration": 15,
        "budget": 100000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop",
        "accommodation": "Twin Sharing in tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Skiing",
        "destinationName": "Manali",
        "packageName": "Heli Skiing",
        "packageDescription": "The heliski terrain in the Himachal Pradesh region of India is nothing short of extraordinary and combined with the stimulating cultural experience of the vibrant Kullu Valley, it is something that is out there on its own in terms of extra special ski and snowboard experiences.",
        "packageHighlights": "upto 12 hours flying time, experienced guides and all permissions",
        "startLocation": "Palchan",
        "finishLocation": "Palchan",
        "groupSize": 7,
        "activityLevel": "Difficult",
        "duration": 6,
        "budget": 1000000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop",
        "accommodation": "Twin Sharing hotel stay",
        "tripStatus": "Active"
    },
    {
        "activityName": "Trekking",
        "destinationName": "Leh",
        "packageName": "Stok Kangri Expedition",
        "packageDescription": "One of the most fascinating places on the planet is Stok Kangri that lies in the beautiful area of Ladakh. Ladakh is located in the northern state of India and is famous for compassion and support of its residents. Leh the capital of Ladakh is situated at the height of 3500-3800 mts of sea level and the most adventurous place for the trekking lovers.",
        "packageHighlights": "Experienced guides, all permissions and mountaineering equipment",
        "startLocation": "Leh",
        "finishLocation": "Leh",
        "groupSize": 12,
        "activityLevel": "Difficult",
        "duration": 12,
        "budget": 100000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop",
        "accommodation": "Twin Sharing hotel stay and tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Trekking",
        "destinationName": "Leh",
        "packageName": "Darcha Trek",
        "packageDescription": "t is one of the popular treks in the Ladakh region that winds onto the Zanskar Valley and passes through several remote villages and ancient monasteries. The Darcha – Padum Trek along the Tsarap River and followed by Lakong river leads one onto the heart of the Zanskar valley after crossing Shingo La at an altitude of 5100meters.",
        "packageHighlights": "Experienced guides, all permissions and trekking equipment",
        "startLocation": "Leh",
        "finishLocation": "Padum",
        "groupSize": 12,
        "activityLevel": "Moderate",
        "duration": 12,
        "budget": 70000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop",
        "accommodation": "Twin Sharing hotel stay and tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Trekking",
        "destinationName": "Gangotri",
        "packageName": "Gaumukh Trek",
        "packageDescription": "Gaumukh Trek is a 46 km trek hiked over a period of 6 days (8 days including drive to and from the trek,) in the Greater Himalayas. It lies in the state of Uttarakhand, begins and ends at the pilgrim town of Gangotri. The trail snakes through the Greater Himalayas within the confines of Gangotri National Park.",
        "packageHighlights": "Experienced guides, all permissions and trekking equipment",
        "startLocation": "Gangotri",
        "finishLocation": "Gangotri",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 7,
        "budget": 30000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing hotel stay and tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Trekking",
        "destinationName": "Gangotri",
        "packageName": "Tapovan Trek",
        "packageDescription": "An eight day itinerary interspersing myth, spirituality, and sensational adventure, the Gaumukh Tapovan Trek takes you around the Gangotri glacier to the site traditionally believed to be mouth of the holy river Ganga. The Gangotri glacial expanse is nearly 24 km long and 6 to 8 km wide, beginning from Gaumukh and extending as far as the Chaukhamba massif around Badrinath. Courtesy of celebrated mountaineers Shipton and Tilman, we have a trek route traversing the entire stretch of this storied land.",
        "packageHighlights": "Experienced guides, all permissions and trekking equipment",
        "startLocation": "Gangotri",
        "finishLocation": "Gangotri",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 8,
        "budget": 30000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing hotel stay and tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Camping",
        "destinationName": "Leh",
        "packageName": "Pang-Gong Tso Lake",
        "packageDescription": "As the name goes this is one of the best camps in Pangong Lake for that perfect camping experience under the clear night sky. Nestled amidst the bank of Pangong Lake in Spangmik,  Whispering Camps has been considered as a heaven for the thrill seekers and the adventurer and it is one of the best camps in Ladakh.",
        "packageHighlights": "lakeview location, luxury tents and evening bon-fires",
        "startLocation": "Leh",
        "finishLocation": "Leh",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 5,
        "budget": 20000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing in tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Camping",
        "destinationName": "Leh",
        "packageName": "Nubra Desert Camping",
        "packageDescription": "The cold desert camp in Ladakh's Nubra Valley marries the sense of the outdoors to all mod-cons. Aimed at tourists who love the best of worlds, Cold desert Camps offers unparalleled creature comforts and service to make visitors consider prolonging their stay.",
        "packageHighlights": "Camel safari, stay in luxury tents and evening bon-fires",
        "startLocation": "Leh",
        "finishLocation": "Leh",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 5,
        "budget": 25000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing in tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Camping",
        "destinationName": "Rishikesh",
        "packageName": "River Camping",
        "packageDescription": "Hidden along the beautiful banks of the Ganga river, close to Rishikesh, we are the only camp with direct access to the river and complete in-house facilities for all kinds of outdoor activties.",
        "packageHighlights": "River rafting, beach camping and evening bon-fires",
        "startLocation": "Rishikesh",
        "finishLocation": "Rishikesh",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 5,
        "budget": 10000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing in tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Camping",
        "destinationName": "Rishikesh",
        "packageName": "Jungle Camping",
        "packageDescription": "This campsite is a perfect adventurous dose that offers multiple adrenaline-rushing activities, riverside views, bird watching activity, and more. With a lot to do around, the campsite stay is featured with regular amenities that boasts a dining area, a well maintained outdoor swimming pool, a separate playing area where one can enjoy the pleasure of indulging in various outdoor games such as volleyball, football, and a memorable hiking experience that takes you down to the nearby river stream.",
        "packageHighlights": "River rafting, beach camping and evening bon-fires",
        "startLocation": "Rishikesh",
        "finishLocation": "Rishikesh",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 5,
        "budget": 10000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing in tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Wildlife",
        "destinationName": "Jim Corbett",
        "packageName": "Birding Workshop",
        "packageDescription": "Bird watching is a standout amongst the most entrancing side interests that has picked up energy over the years and has now turned into an incredible source of entertainment for some",
        "packageHighlights": "Birding instructions, jungle stay and evening bon-fires",
        "startLocation": "Ramnagar",
        "finishLocation": "Ramnagar",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 7,
        "budget": 30000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing in hotel and tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Wildlife",
        "destinationName": "Jim Corbett",
        "packageName": "Jungle Safari",
        "packageDescription": "The place is known for its jeep safari inside the national park. Here you can spot elephants, monkeys, leopards, red fox, black bears, and of course, the Bengal tiger. Make sure you don’t step outside the jeep and enjoy the picturesque view from the inside.",
        "packageHighlights": "Jungle lodge stay, jeep safari and evening bon-fires",
        "startLocation": "Ramnagar",
        "finishLocation": "Ramnagar",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 10,
        "budget": 60000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing in hotel, lodges and tents",
        "tripStatus": "Active"
    },
    {
        "activityName": "Wildlife",
        "destinationName": "Ranthambore",
        "packageName": "Elephant Safari",
        "packageDescription": "Ranthambore National Park is one of the biggest and most renowned national parks in Northern India. The park is located in the Sawai Madhopur district of southeastern Rajasthan, which is about 130 km from Jaipur.",
        "packageHighlights": "Jungle lodge stay, elephant back safari and evening bon-fires",
        "startLocation": "Sawai Madhopur",
        "finishLocation": "Sawai Madhopur",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 4,
        "budget": 50000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing in hotel and lodges.",
        "tripStatus": "Active"
    },
    {
        "activityName": "Wildlife",
        "destinationName": "Ranthambore",
        "packageName": "Naturalist Course",
        "packageDescription": "provides the participants the enriching experience of learning in a boot-camp setting with limited phone and internet connectivity. For those wanting to take a break from the routine city life, this course offers a quintessential format for inculcating new hobbies like species identification, or interpreting tracks and signs.",
        "startLocation": "Sawai Madhopur",
        "finishLocation": "Sawai Madhopur",
        "groupSize": 12,
        "activityLevel": "Easy",
        "duration": 20,
        "budget": 100000,
        "meals": "All Meals",
        "transport": "Airport Pick and Drop & travel by road to start point",
        "accommodation": "Twin Sharing in hotel and lodges.",
        "tripStatus": "Active"
    },
]
